
name: First Workflow
on: workflow_dispatch
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello!"
      - name: print goodbye
        run: echo "Done - Bye!"

